<?php $this->itemsperpage?>
<html>
<head>
<style>
li{
	list-style-type: none;
	display: inline;
}
.filter, form, .paginator{
	display: inline;
}
.paginator div , .paginator div ul{
	display: inline;
}
table{
	width:100%;
}
</style>
</head>
<body>
	<div style="display: block; text-align: right; padding: 10px;">
		<div class="paginator">
			<?php echo $this->paginationControl( $this->paginator,'Sliding','index/paginator_control.phtml'); ?>
		</div>
	</div>
	<table border="1">
		<tr>
			<th>Code</th>
			<th>Name</th>
			<th>Continent</th>
			<th>Region</th>
			<th>SurfaceArea</th>
			<th>Independence</th>
			<th>Population</th>
			<th>LifeExpectancy</th>
			<th>GNP</th>
			<th>GNPOld</th>
			<th>LocalName</th>
			<th>GovernamentForm</th>
			<th>HeadOfState</th>
			<th>Capital</th>
			<th>Code2</th>
		</tr>
		<?php	foreach ( $this->paginator as $user ){ ?>
		<tr>
			<td><?= $user['Code'] ?></td>
			<td><?= $user['Name'] ?></td>
			<td><?= $user['Continent'] ?></td>
			<td><?= $user['Region'] ?></td>
			<td><?= $user['SurfaceArea'] ?></td>
			<td><?= $user['IndepYear'] ?></td>
			<td><?= $user['Population'] ?></td>
			<td><?= $user['LifeExpectancy'] ?></td>
			<td><?= $user['GNP'] ?></td>
			<td><?= $user['GNPOld'] ?></td>
			<td><?= $user['LocalName'] ?></td>
			<td><?= $user['GovernmentForm'] ?></td>
			<td><?= $user['HeadOfState'] ?></td>
			<td><?= $user['Capital'] ?></td>
			<td><?= $user['Code2'] ?></td>
		</tr>
		<?php }?>
	</table>
</body>
</html>